/***********************************************************************

weapon_pistol_flashlight.script

***********************************************************************/

#define PISTOL_FLASHLIGHT_FIRERATE			0.4
#define PISTOL_FLASHLIGHT_LOWAMMO			4
#define PISTOL_FLASHLIGHT_NUMPROJECTILES	1

// blend times
#define PISTOL_FLASHLIGHT_IDLE_TO_LOWER	2
#define PISTOL_FLASHLIGHT_IDLE_TO_FIRE		1
#define	PISTOL_FLASHLIGHT_IDLE_TO_RELOAD	3
#define PISTOL_FLASHLIGHT_RAISE_TO_IDLE	2
#define PISTOL_FLASHLIGHT_FIRE_TO_IDLE		3
#define PISTOL_FLASHLIGHT_RELOAD_TO_IDLE	1

float global_flashlight_intensity = 1.0;		// for dimming flashlight during plasma discharges in alphalabs2

object weapon_pistol_flashlight : weapon_base {
	float		next_attack;
	float		spread;

	float		intensity;						// Credit to capri91 for ductape mod logic concept
	
	void		init();
	
	void		Lower();
	void		Raise();
	void		Idle();
	void		Fire();
	void		Reload();
	void 		EnterCinematic();
	void		ExitCinematic();
	void 		updateLightIntensity();
};

void weapon_pistol_flashlight::init() {
	next_attack = 0;
	spread		= getFloatKey( "spread" );
	weaponState( "Raise", 0 );

	intensity = 1.0;
	setLightParm( 3, 1.0 );
	setShaderParm( 3, 1.0 );
}

void weapon_pistol_flashlight::updateLightIntensity() {
	if (global_flashlight_intensity != intensity) {
		intensity = global_flashlight_intensity;
		setLightParm( 3, intensity );
		setShaderParm( 3, intensity );
	} 
}

void weapon_pistol_flashlight::Raise() {
	// smolspacer - Match ammo in clip to that of the flashlight pistol
	setClip(g_pistol_clip_remaining);
	
	weaponRising();

	if (ammoInClip() > 0) {						// smolspacer
		playAnim( ANIMCHANNEL_ALL, "raise" );
	}
	else {
		playAnim( ANIMCHANNEL_ALL, "raise_empty" );
	}
	flashlight( true );
	waitUntil( animDone( ANIMCHANNEL_ALL, PISTOL_FLASHLIGHT_RAISE_TO_IDLE ) );
	weaponState( "Idle", PISTOL_FLASHLIGHT_RAISE_TO_IDLE );
}

void weapon_pistol_flashlight::Lower() {
	// smolspacer
	g_pistol_clip_remaining = ammoInClip();

	weaponLowering();
	if (ammoInClip() > 0) {						// smolspacer
		playAnim( ANIMCHANNEL_ALL, "putaway" );
	}
	else {
		playAnim( ANIMCHANNEL_ALL, "putaway_empty" );

	}
	waitUntil( animDone( ANIMCHANNEL_ALL, 0 ) );
	weaponHolstered();
	waitUntil( WEAPON_RAISEWEAPON );
	weaponState( "Raise", 0 );
}

void weapon_pistol_flashlight::Idle() {
	float currentTime;
	float ammoClip;
	float avail;
	float clip_size;
	
	clip_size = clipSize();	
	
	weaponReady();
	if ( !ammoInClip() ) {
		playCycle( ANIMCHANNEL_ALL, "idle_empty" );
	} else {
		playCycle( ANIMCHANNEL_ALL, "idle" );
	}
	while( 1 ) {
		updateLightIntensity();
		if ( WEAPON_LOWERWEAPON ) {
			weaponState( "Lower", PISTOL_FLASHLIGHT_IDLE_TO_LOWER );
		}
		currentTime = sys.getTime();
		ammoClip = ammoInClip();
		if ( ( currentTime >= next_attack ) && WEAPON_ATTACK ) {
			if ( ammoClip > 0 ) {
				weaponState( "Fire", PISTOL_FLASHLIGHT_IDLE_TO_FIRE );
			} else {
				startSound("snd_pistol_empty", SND_CHANNEL_WEAPON, true);
				next_attack = sys.getTime() + PISTOL_FLASHLIGHT_FIRERATE;
				if ( ammoAvailable() > 0 ) {
					if ( autoReload() ) {
						netReload();
						weaponState( "Reload", PISTOL_FLASHLIGHT_IDLE_TO_RELOAD );
					}
				}
			}
		}
		if ( WEAPON_RELOAD && ( ammoAvailable() > ammoClip ) && ( ammoClip < clip_size ) ) {
			netReload();
			weaponState( "Reload", PISTOL_FLASHLIGHT_IDLE_TO_RELOAD );
		}
		if ( WEAPON_NETRELOAD ) {
			WEAPON_NETRELOAD = false;
			weaponState( "Reload", PISTOL_FLASHLIGHT_IDLE_TO_RELOAD );		
		}
		waitFrame();
	}
}

void weapon_pistol_flashlight::Fire() {
	float ammoClip;

	next_attack = sys.getTime() + PISTOL_FLASHLIGHT_FIRERATE;
	
	ammoClip = ammoInClip();
	if ( ammoClip == PISTOL_FLASHLIGHT_LOWAMMO ) {
		startSound( "snd_lowammo", SND_CHANNEL_ITEM, true );
	}
	
	launchProjectiles( PISTOL_FLASHLIGHT_NUMPROJECTILES, spread, 0, 1.0, 1.0 );
	if ( ammoClip > 1 )	{		// smolspacer
		playAnim( ANIMCHANNEL_ALL, "fire" );
	}
	else if (ammoClip == 1) {
		playAnim( ANIMCHANNEL_ALL, "fire1_to_empty");
	}
	while (!animDone( ANIMCHANNEL_ALL, PISTOL_FLASHLIGHT_FIRE_TO_IDLE )) {
		updateLightIntensity();
		waitFrame();
	}
	weaponState( "Idle", PISTOL_FLASHLIGHT_FIRE_TO_IDLE );
}

void weapon_pistol_flashlight::Reload() {
	weaponReloading();
	if (ammoInClip() > 0) {				// smolspacer
		playAnim( ANIMCHANNEL_ALL, "reload_noempty" );
	}
	else {
		playAnim( ANIMCHANNEL_ALL, "reload_empty" );
	}
	while (!animDone( ANIMCHANNEL_ALL, PISTOL_FLASHLIGHT_RELOAD_TO_IDLE )) {
		updateLightIntensity();
		waitFrame();
	}
	addToClip( clipSize() );
	weaponState( "Idle", PISTOL_FLASHLIGHT_RELOAD_TO_IDLE );
}

void weapon_pistol_flashlight::EnterCinematic() {
	flashlight(false);
	weaponState("Idle", 0);
}

void weapon_pistol_flashlight::ExitCinematic() {
	next_attack = 0;
	updateLightIntensity();
	flashlight( true );
	weaponState( "Idle", 0 );
}
